### ISSUE TITLE
Install and setup guide

### ISSUE THREAD

**Issue by tkang007** [timkpaine/paperboy#44]
Hi,

I am looking for papermill notebook executing web front end solution.  
Paperboy looks like perfect matching with my requirements.

So, I need your help for basic testing with install and setup guide.

I have clone your project and installed python and js packages, build and installed with Makefile.
Started the server with 'make run' and accessible from browser. 

I have problem with below log: 
CRITICAL:root:list : <class 'paperboy.storage.sqla.models.notebook.NotebookSQL'>, result : 3 - 3
CRITICAL:root:list : <class 'paperboy.storage.sqla.models.job.JobSQL'>, result : 0 - 0
CRITICAL:root:list : <class 'paperboy.storage.sqla.models.report.ReportSQL'>, result : 0 - 0
CRITICAL:root:list : <class 'paperboy.storage.sqla.models.notebook.NotebookSQL'>, result : 3 - 3
'AirflowScheduler' object has no attribute 'engine'
'AirflowScheduler' object has no attribute 'engine'
'AirflowScheduler' object has no attribute 'engine'
'AirflowScheduler' object has no attribute 'engine'

Getting Started file might not be ready at the docs directory.

Could you give me some idea what I have missed, or where I can find any introduction file ?

Thanks

**Comment by tkang007** [comment]
Great! I will try

**Comment by timkpaine** [comment]
https://github.com/timkpaine/paperboy#installation-from-source

We will set up a CONTRIBUTING.md #69
