### ISSUE TITLE
Rename/Release

### ISSUE THREAD

**Issue by blink1073** [timkpaine/paperboy#67]
I'd like to help get this released on PyPI and conda-forge.

However, paperboy is taken on PyPI: https://pypi.org/project/Paperboy/

It was last published 5 years ago by Edgeflip, a software startup: https://www.linkedin.com/company/edgeflip/about/

The last activity on the repo is also from 5 years ago: https://github.com/edgeflip/dispatch

Options:
- Reach out to EdgeFlip directly and see if they will relinquish the name on PyPI
- Ask PyPA to remove it: https://www.python.org/dev/peps/pep-0541/
- Pick a different name

**Comment by timkpaine** [comment]
Probably 1,2,3 in that order

**Comment by blink1073** [comment]
cf https://github.com/edgeflip/dispatch/issues/2

**Comment by blink1073** [comment]
So, new options
- different PyPI name but same lib and import name (scikit-image imports as skimage)
- new name - deliveryman?

**Comment by timkpaine** [comment]
I'm ok with different PyPi name, it is a bit annoying that dispatch imports as dispatch and basically does not use the paperboy name: https://github.com/edgeflip/dispatch/tree/master/dispatch

**Comment by timkpaine** [comment]
If we get adoption we can always hostile takeover the name :-)

**Comment by blink1073** [comment]
https://pypi.org/project/jupyter-paperboy/, I added you as an owner @timkpaine

**Comment by blink1073** [comment]
conda forge coming tomorrow

**Comment by blink1073** [comment]
conda forge done!
