### ISSUE TITLE
Collaborate to add the Argo backend

### ISSUE THREAD

**Issue by ktaletsk** [timkpaine/paperboy#85]
**Is your feature request related to a problem? Please describe.**
I've been working on somewhat similar project for scheduling Notebook execution that utilizes Kubernetes Argo (https://argoproj.github.io/argo) backend and S3 storage: https://github.com/ktaletsk/yason. 

**Describe the solution you'd like**
I just discovered this project on the JupyterLab dev call and wonder if you will be interested to combine forces and add Argo backend to the paperboy?

**Describe alternatives you've considered**

**Additional context**

**Comment by timkpaine** [comment]
@ktaletsk sure. There are 3 schedulers supported right now (to varying degrees) so it should be easy enough to see the commonalities. For S3 it will be easier once i finish the mongo backend https://github.com/timkpaine/paperboy/issues/58 and https://github.com/timkpaine/paperboy/tree/mongodb

**Comment by timkpaine** [comment]
#58
